name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main   # <-- change this to 'portfolio-update' if you want that branch to trigger deploys

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare publish directory
        # copy site files to a clean ./public directory, excluding git and workflow files
        run: |
          rm -rf public
          mkdir -p public
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publishing_branch: gh-pages    # default is gh-pages; uncomment to set explicitly
